# TODO: integrate with Cordova build
# https://gist.github.com/LinusU/7515016

inkscape -z -w  36 -h  36 -e "./phonegap-build/platforms/android/res/drawable-ldpi/icon.png"  "./sheepshead.svg"
inkscape -z -w  72 -h  72 -e "./phonegap-build/platforms/android/res/drawable-mdpi/icon.png"  "./sheepshead.svg"
inkscape -z -w  48 -h  48 -e "./phonegap-build/platforms/android/res/drawable-hdpi/icon.png"  "./sheepshead.svg"
inkscape -z -w  96 -h  96 -e "./phonegap-build/platforms/android/res/drawable-xhdpi/icon.png" "./sheepshead.svg"
inkscape -z -w  96 -h  96 -e "./phonegap-build/platforms/android/res/drawable/icon.png"       "./sheepshead.svg"

inkscape -z -w  40 -h  40 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon-40.png"       "./sheepshead.svg"
inkscape -z -w  80 -h  80 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon-40@2x.png"    "./sheepshead.svg"
inkscape -z -w  50 -h  50 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon-50.png"       "./sheepshead.svg"
inkscape -z -w 100 -h 100 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon-50@2x.png"    "./sheepshead.svg"
inkscape -z -w  60 -h  60 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon-60.png"       "./sheepshead.svg"
inkscape -z -w 120 -h 120 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon-60@2x.png"    "./sheepshead.svg"
inkscape -z -w  72 -h  72 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon-72.png"       "./sheepshead.svg"
inkscape -z -w 144 -h 144 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon-72@2x.png"    "./sheepshead.svg"
inkscape -z -w  76 -h  76 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon-76.png"       "./sheepshead.svg"
inkscape -z -w 154 -h 154 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon-76@2x.png"    "./sheepshead.svg"
inkscape -z -w  29 -h  29 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon-small.png"    "./sheepshead.svg"
inkscape -z -w  58 -h  58 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon-small@2x.png" "./sheepshead.svg"
inkscape -z -w  57 -h  57 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon.png"          "./sheepshead.svg"
inkscape -z -w 114 -h 114 -e "./phonegap-build/platforms/ios/Sheepshead Mobile/Resources/icons/icon@2x.png"       "./sheepshead.svg"

# convert="convert $1 -background $2 -gravity center"
# $convert -resize 512x512 -extent 1280x720 "$3/res/screen/android/screen-xhdpi-landscape.png"
# $convert -resize 256x256 -extent 480x800 "$3/res/screen/android/screen-hdpi-portrait.png"
# $convert -resize 128x128 -extent 320x200 "$3/res/screen/android/screen-ldpi-landscape.png"
# $convert -resize 512x512 -extent 720x1280 "$3/res/screen/android/screen-xhdpi-portrait.png"
# $convert -resize 256x256 -extent 320x480 "$3/res/screen/android/screen-mdpi-portrait.png"
# $convert -resize 256x256 -extent 480x320 "$3/res/screen/android/screen-mdpi-landscape.png"
# $convert -resize 128x128 -extent 200x320 "$3/res/screen/android/screen-ldpi-portrait.png"
# $convert -resize 256x256 -extent 800x480 "$3/res/screen/android/screen-hdpi-landscape.png"
# $convert -resize 256x256 -extent 320x480 "$3/res/screen/ios/screen-iphone-portrait.png"
# $convert -resize 256x256 -extent 960x640 "$3/res/screen/ios/screen-iphone-landscape-2x.png"
# $convert -resize 256x256 -extent 480x320 "$3/res/screen/ios/screen-iphone-landscape.png"
# $convert -resize 512x512 -extent 768x1004 "$3/res/screen/ios/screen-ipad-portrait.png"
# $convert -resize 1024x1024 -extent 1536x2008 "$3/res/screen/ios/screen-ipad-portrait-2x.png"
# $convert -resize 512x512 -extent 1024x783 "$3/res/screen/ios/screen-ipad-landscape.png"
# $convert -resize 256x256 -extent 640x960 "$3/res/screen/ios/screen-iphone-portrait-2x.png"
# $convert -resize 1024x1024 -extent 2008x1536 "$3/res/screen/ios/screen-ipad-landscape-2x.png"
